version: "3"
services:
  mysqld:
    image: mysql
    container_name: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=rentzone
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
    volumes:
      - ./rentzone-db.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
volumes:
  data:
secrets:
  mysql_root_password:
    file: ./env/MYSQL_ROOT_PASSWORD
  mysql_user:
    file: ./env/MYSQL_USER
  mysql_password:
    file: ./env/MYSQL_PASSWORD
